#!/usr/bin/env python3
"""
AIOS Git Hooks Installer

Cross-platform script to install AIOS governance hooks into .git/hooks/.
Works on Windows (cmd/PowerShell) and Mac/Linux (bash/zsh).

Usage:
    python AIOShooks/install_hooks.py          # Install hooks
    python AIOShooks/install_hooks.py --check  # Check installation status
    python AIOShooks/install_hooks.py --remove # Remove installed hooks
"""

import argparse
import os
import platform
import shutil
import stat
import sys

# Resolve paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, '..'))
GIT_HOOKS_DIR = os.path.join(PROJECT_ROOT, '.git', 'hooks')

HOOKS = ['pre-commit', 'pre-push', 'post-merge']


def check_git_repo():
    """Verify we're in a git repository."""
    git_dir = os.path.join(PROJECT_ROOT, '.git')
    if not os.path.isdir(git_dir):
        print("Error: Not a git repository. Run 'git init' first.")
        return False
    return True


def ensure_hooks_dir():
    """Ensure .git/hooks/ directory exists."""
    os.makedirs(GIT_HOOKS_DIR, exist_ok=True)


def is_windows():
    """Check if running on Windows."""
    return platform.system() == 'Windows'


def install_hook(hook_name):
    """Install a single hook."""
    source = os.path.join(SCRIPT_DIR, hook_name)
    if not os.path.exists(source):
        print(f"  Warning: Source hook not found: {source}")
        return False

    if is_windows():
        # On Windows, Git for Windows can run Python scripts directly
        # Create a wrapper that calls python with the hook script
        target = os.path.join(GIT_HOOKS_DIR, hook_name)
        hook_path = os.path.abspath(source).replace('\\', '/')

        wrapper_content = f"""#!/bin/sh
# AIOS Hook Wrapper (auto-generated by install_hooks.py)
python "{hook_path}" "$@"
exit 0
"""
        with open(target, 'w', encoding='utf-8', newline='\n') as f:
            f.write(wrapper_content)
    else:
        # On Mac/Linux, create symlink or copy
        target = os.path.join(GIT_HOOKS_DIR, hook_name)
        try:
            # Try symlink first
            rel_path = os.path.relpath(source, GIT_HOOKS_DIR)
            if os.path.exists(target):
                os.remove(target)
            os.symlink(rel_path, target)
        except (OSError, NotImplementedError):
            # Fallback to copy
            shutil.copy2(source, target)

        # Make executable
        st = os.stat(target)
        os.chmod(target, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    return True


def remove_hook(hook_name):
    """Remove an installed hook."""
    target = os.path.join(GIT_HOOKS_DIR, hook_name)
    if os.path.exists(target):
        os.remove(target)
        return True
    return False


def check_hook(hook_name):
    """Check if a hook is installed."""
    target = os.path.join(GIT_HOOKS_DIR, hook_name)
    return os.path.exists(target)


def cmd_install():
    """Install all hooks."""
    if not check_git_repo():
        return

    ensure_hooks_dir()
    system = platform.system()
    print(f"Installing AIOS hooks ({system})...\n")

    success = 0
    for hook in HOOKS:
        if install_hook(hook):
            print(f"  [OK] {hook}")
            success += 1
        else:
            print(f"  [FAIL] {hook}")

    print(f"\n{success}/{len(HOOKS)} hooks installed to {GIT_HOOKS_DIR}")
    print("\nHooks are warn-only (v1). They will never block your commits.")


def cmd_check():
    """Check installation status."""
    if not check_git_repo():
        return

    print("AIOS Hook Installation Status:\n")
    all_ok = True
    for hook in HOOKS:
        installed = check_hook(hook)
        status = "[OK] installed" if installed else "[--] not installed"
        print(f"  {hook}: {status}")
        if not installed:
            all_ok = False

    if not all_ok:
        print("\nRun 'python AIOShooks/install_hooks.py' to install missing hooks.")


def cmd_remove():
    """Remove all hooks."""
    print("Removing AIOS hooks...\n")
    for hook in HOOKS:
        if remove_hook(hook):
            print(f"  [OK] Removed {hook}")
        else:
            print(f"  [--] {hook} was not installed")

    print("\nDone.")


def main():
    parser = argparse.ArgumentParser(
        description='AIOS Git Hooks Installer — Cross-platform hook management',
        epilog='Part of the AIOS Memo-Driven Development Workflow'
    )
    parser.add_argument(
        '--check', action='store_true',
        help='Check installation status'
    )
    parser.add_argument(
        '--remove', action='store_true',
        help='Remove installed hooks'
    )

    args = parser.parse_args()

    if args.check:
        cmd_check()
    elif args.remove:
        cmd_remove()
    else:
        cmd_install()


if __name__ == '__main__':
    main()
